# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.conf                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetros <tpetros@student.42abudhabi.ae>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/03 16:23:13 by tpetros           #+#    #+#              #
#    Updated: 2024/01/03 16:23:14 by tpetros          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

