# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetros <tpetros@student.42abudhabi.ae>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/03 16:23:13 by tpetros           #+#    #+#              #
#    Updated: 2024/01/03 16:23:14 by tpetros          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    # volumes:
    #   - ./requirements/nginx/conf/:/etc/nginx/http.d/
    #   - ./requirements/nginx/tools:/etc/nginx/ssl/
    #   - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    # volumes:
    #   - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
#     volumes:
#       - wp-volume:/var/www/

# volumes:
#   wp-volume:
#     driver_opts:
#       o: bind
#       type: none
#       device: /root/data/wordpress

#   db-volume:
#     driver_opts:
#       o: bind
#       type: none
#       device: /root/data/mariadb

networks:
    inception:
        driver: bridge