version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - InceptionNetwork
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      WP_DB_NAME : ${WP_DB_NAME}
      DB_USER : ${DB_USER}
      DB_PASSWD : ${DB_PASSWD}
      DB_ROOT_PASSWD : ${DB_ROOT_PASSWD}
    ports:
      - "6969:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - InceptionNetwork
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_USER: ${WP_USER}
      WP_PASSWD: ${WP_PASSWD}
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always
    networks:
      - InceptionNetwork

networks:
  InceptionNetwork:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      o: bind
      type: none
      device: /home/tpetros/data/db
  wp_data:
    driver_opts:
      o: bind
      type: none
      device: /home/tpetros/data/wp
